name: Java CI/CD with Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # 1. ARM64 빌드를 위한 QEMU 및 Buildx 설정
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 2. 도커 허브 로그인 (ECR 로그인 대신 사용)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. ARM64 플랫폼 지정 빌드 및 푸시
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/stolink-spring:latest

    # 4. EC2 배포 (docker-compose 방식)
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }} # 보통 ubuntu 또는 ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/stolink-project
          # 도커 허브 로그인이 필요할 경우 수행
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          # 최신 이미지 가져오기
          docker compose pull spring
          # 컨테이너 재시작 (spring 서비스만)
          docker compose up -d spring
          # 사용하지 않는 이전 이미지 정리
          docker image prune -f
